### ISSUE TITLE
[Modules/Frontend] make sure modules understand auth

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_CityIO#102]
As we are about to have authenticated users and restricted tables, modules need to be aware of adding info to the header of their HTTP request.

Modules will have to 
```
Authorization: Bearer LONG_TOKEN_PROVIDED_BY_YASUSHI
```
to their requests.

**Comment by RELNO** [comment]
It should be noted not to commit the token with your modules.

**Comment by yasushisakai** [comment]
Related to this, I want to ask for you what method we prefer for storing secret keys and API tokens. [`dotenv`](https://pypi.org/project/python-dotenv/) seems something consistent across other languages and frameworks.

**Comment by yasushisakai** [comment]
there is no upcoming need to ensure auth... at... the... moment
