### ISSUE TITLE
Change in hidden table API?

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO#109]
https://cityscope.media.mit.edu/CS_CityIO/ can no longer fetch `hidden-table` thus it returns an error.

**Comment by yasushisakai** [comment]
what do we mean by Lat-Lng API?

**Comment by yasushisakai** [comment]
`curl -H "Authorization:Bearer {SECRET}" https://cityio.media.mit.edu/api/table/hidden_table | jq '.header'`

tells me there is no location. (jq is a json parser for commandline)

**Comment by RELNO** [comment]
Wrong title -- the issue is with hidden tables.

In the current version of cityIO FE, this is how we get a table:
```
/**
 * get cityIO method [uses polyfill]
 * @param cityIOtableURL cityIO API endpoint URL
 */
async function getCityIO(url) {
  var myHeaders = {
    headers: new Headers({
      Authorization:
        "Bearer ________"
    })
  };

  return fetch(url, myHeaders)
    .then(function(response) {
      return response.json();
    })
    .then(function(cityIOdata) {
      return cityIOdata;
    })
    .catch(err => {
      console.log(err);
    });
}

```

Bearer is hardcoded in the FE. We agreed on getting it this way, since we otherwise cannot parse 
```
  let cityIOurl = "https://cityio.media.mit.edu/api/tables/list";
  const tables = await getCityIO(cityIOurl);
```

What is an alternative to this? is there a way for me to know in advance which table is hidden?
