### ISSUE TITLE
User authentification fails

### ISSUE THREAD

**Issue by andredaa** [CityScope/CS_CityIO#110]
The user authentification fails from the browser app of grasbrook city scope. 
Strange thing is it worked before and with no changes auth stopped working. 
Getting 400 bad request. 
Chrome says we are blocked by CORS
https://files.slack.com/files-pri/TD6HGUD6V-FR43JH2UV/image.png

**Comment by yasushisakai** [comment]
can you check if you can authenticate via postman or curl?

**Comment by yasushisakai** [comment]
done.

**Comment by andredaa** [comment]
thank you!
