### ISSUE TITLE
API examples

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_CityIO#113]
I am trying to build the Radar module in python and I found out that there are not "examples" of API for python either for JS or other formats (C++, C, fortran Assembly, etc.)  ;)

Do we have it somewhere? Is it possible to update this list?

**Comment by RELNO** [comment]
@LAAP as mentioned, I suggest you explore https://github.com/CityScope/CS_CityIO/tree/master/cityio_modules to see how current cityIO fetching happens in python. 
As for other fetching formats, this sure be useful but also requires frequent maintenance, as cityIO changes over time. You can start with [HTTP requests in Scratch ;)](https://en.scratch-wiki.info/wiki/Scratch_Extension#HTTP_Extensions)

**Comment by doorleyr** [comment]
@LAAP I made a simple module template in python. You can find it here:
https://github.com/doorleyr/CS_Module_Template
It handles all the routine stuff like checking fro changes to the grid data, getting the new grid data and posting the module results to cityI/O. You just need to fill in the initialise() and perform_updates() functions for your specific tasks. I can work on this with you if you want.

**Comment by LAAP** [comment]
Hi  @RELNO and @doorleyr , Thanks for answering.

@doorleyr , Yes, this is useful If you do not mind, I would love to develop the module with your help. Let's catch up by email

**Comment by yasushisakai** [comment]
closing since @LAAP seems happy with the responses

**Comment by agrignard** [comment]
@yasushisakai I am reopening this issue even if it's sounds old just to see with you where do you think would be a good places to have different module exemple? I'd like for instance to update the GAMA one which is so far here
https://github.com/CityScope/CS_CityIO/tree/master/examples/GAMA/cityIO_Gama

Is this still an option?

and what about this folder?
https://github.com/CityScope/CS_CityIO/tree/master/cityio_modules

**Comment by RELNO** [comment]
@agrignard once option would be to write directly into the docs, similar to birx: https://cityscope.media.mit.edu/docs/modules/Brix/Brix

**Comment by yasushisakai** [comment]
`cityio_modules` was an effort form @Ariel to have a python module to make it easier to communicate with cityioIO, I would say it's similar to Brix (Except that it was focused for more general purposes). If I'm not mistaken.

As for the examples, I'm up for however people wants. We have now a great doc infrastructure, but if you want to have examples 'here' that's fine too. Just push it to the master or do a PR and I will accept it. I do think its worth trying the doc infrastructure having step by step tutorial using gama might be good, but again up to you.

**Comment by agrignard** [comment]
Ok so you think it's better to push it in the doc github?

**Comment by RELNO** [comment]
<img width="383" alt="Screen Shot 2020-10-27 at 11 02 05" src="https://user-images.githubusercontent.com/14296774/97320092-da57e180-1843-11eb-8b7c-90ae22ed2691.png">

**Comment by RELNO** [comment]
> Ok so you think it's better to push it in the doc github?

If the example is not super long, I'd say yes -- I can show you how to add the `md` file to the docsite

**Comment by yasushisakai** [comment]
yeah, I would give it a try (I know I have incomplete documentation for cityio)

**Comment by agrignard** [comment]
Ok so  I will work in this repo
https://github.com/CityScope/CS_Simulation_GAMA
and update the Readme that can then be linked in the doc.

I'll start here and let's see how it goes and let's keep discussing this on this specific issue
https://github.com/CityScope/CS_Simulation_GAMA/issues/135
