### ISSUE TITLE
odd field upon (assumed) database recovery 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO#114]
@ Grasbrook endpoint, this is returned from grid filed: 
<img width="549" alt="Screen Shot 2019-12-12 at 20 51 19" src="https://user-images.githubusercontent.com/14296774/70763184-36e00a00-1d21-11ea-9f97-6e490c1a6da5.png">
Assuming this is a product of db recovery, might worth recovering with either last grid/ nulled?

**Comment by yasushisakai** [comment]
weird. I don't recall putting this behaviour from the serverside.... (server should inject it in the meta field)

**Comment by yasushisakai** [comment]
I've checked my own code, it looks like the request was handled as intended through ```/grasbrook/grid``` (deep get) endpoint. 

so currently, it's giving an (error)`object`. 

**What's your preferred behavior for this?**

If the database holds some `/grasbrook/xxx` it will show it.  If it couldn't find it for a reason (either not in the database or deleted) should it give a `null` or `[]` or an error object? it can be raised to an HTTP status code if we want to.

**Comment by RELNO** [comment]
> What's your preferred behavior for this?
If the database holds some /grasbrook/xxx it will show it. If it couldn't find it for a reason (either not in the database or deleted) should it give a null or [] or an error object? it can be raised to an HTTP status code if we want to.

If `grid` (for example) lived before the crash, it would be good if it could be restored as it was. Otherwise, if the db cannot restore it -- or any other field -- I'd suggest the field itself won't be present. The reason is, it's more common to learn of a missing field via `meta` thu a simple `GET` rather than parsing several fields only to have on of them empty/null (which is the case now for GB grid)

**Comment by yasushisakai** [comment]
so 404 or a similar status code is better?

**Comment by RELNO** [comment]
> so 404 or a similar status code is better?
isolating the deep get behavior

Actually the error we get now is good enough -- so to clarify: if db cannot restore a field, simply omit the entire field (don't leave empty etc) . I'm still not clear though as to why grid is missing -- is this by design?

**Comment by yasushisakai** [comment]
ver3 uses status code 404 to indicate it is missing. Re-open if this behavior is misleading or want to change to a different one.
