### ISSUE TITLE
Add script/docs to restart cityio remotely 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO#115]

**Comment by RELNO** [comment]
would be great time to reconsider this, thanks.

**Comment by yasushisakai** [comment]
for restarting the server, [here](https://cityscope.media.mit.edu/backend/Build) and [here](https://github.com/CityScope/cityscope.github.io/blob/new_docsite/docsite/docs/backend/Internal_Note.md) will be the places to look.
