### ISSUE TITLE
CURL cert is out of date

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO#122]
When trying to `$ curl`: 
```
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by yasushisakai** [comment]
I'll request ssl cert renewal for this, meanwhile you can `curl -k`

**Comment by yasushisakai** [comment]
I've requested renewal of the ssl certificates, but we might need this too.

http://kb.mit.edu/confluence/display/mitcontrib/Use+curl+to+read+certificate+protected+web+pages

**Comment by RELNO** [comment]
Thanks. I wonder if the ML domains fall under the same category.

**Comment by yasushisakai** [comment]
closing this since we renewed the certificate.
