### ISSUE TITLE
Cannot build the server because of local sha256 package

### ISSUE THREAD

**Issue by mgijsbertihodenpijl** [CityScope/CS_CityIO#123]
Hi,

i am trying to build the server by running ```cargo build ``` but the build fails on the sha256.
In cargo.tom I see that sha256 is a locally installed package. But which one and which version ?

```
error[E0432]:` unresolved import `sha256::sha256`
  --> src/lib.rs:18:13
   |
18 | use sha256::sha256::{format_hash, hash};
   |             ^^^^^^ could not find `sha256` in `sha256`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `cs_cityio_backend`.

To learn more, run the command again with --verbose.
```

**Comment by yasushisakai** [comment]
Hi @mgijsbertihodenpijl,

latest bd0e0d51ed2aad5958275edaa2491914b6f7dfe8 commit's
`Cargo.toml` points to a git repo now, this will at least make it possible to build.

This will go away once I update the actix framework to 3.0,
and use a standard implementation of hash functions.

**Comment by mgijsbertihodenpijl** [comment]
Thanks!

**Comment by mgijsbertihodenpijl** [comment]
Works!
