### ISSUE TITLE
cityScope and GAMA

### ISSUE THREAD

**Issue by mgijsbertihodenpijl** [CityScope/CS_CityIO#124]
Hi,

We are a service company (https://schubergphilis.com/) and we are experimenting with the tangible table with Lego from MIT and GAMA. We want to use this for modelling problems of our customers (smart factory, energy, supply chain, etc). 

We are trying to understand how the whole platform works and how we can use it together with GAMA. Especially we are interested if we can send back information from agents in GAMA back to the tangible table, so we can modelling for instance traffic of agents and delivery times in real time. Is this possible with cityScope and is there some documentation about how all these components fit together ? 

Thanks, Martijn

**Comment by crisjf** [comment]
Hi Martijn, 

We just started working on a more user-friendly GAMA integration. 

Here's the (brand new) documentation for connecting a GAMA model to a CityScope table:
https://cityscope.media.mit.edu/docs/modules/GAMA/

You will need the `GAMABrix.gaml` file. You can find that here:
https://github.com/CityScope/CS_Simulation_GAMA/tree/master/CS_CityScope_GAMA/models/cityIO/models

Let us know in this thread if things are unclear, as you would actually be the first user using this new module. We're very much looking forward to your feedback on the documentation.

I'm also tagging @agrignard who is one of the developers of GAMA.

Best,
Cris

**Comment by yasushisakai** [comment]
closing this since this is more of an application layer. Re-open if there is server-side thing to do for integrating simulation modules.
