### ISSUE TITLE
Cannot clone table from cityio into cityiotest

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_CityIO#125]
I'm trying to clone a table from cityio.

First, I get the table from cityio
```
curl https://cityio.media.mit.edu/api/table/dungeonmaster --output dungeonmaster_dump.json
```

Then I try to post it using the following:
```
curl -X POST -H "Content-Type:application/json" -d @dungeonmaster_dump.json https://cityiotest.mirage.city/api/table/dungeonmaster/
```

It returns 502 Bad Gateway.

Interestingly, this works:
```
curl -X POST -H "Content-Type:application/json" -d '{"grid":[0,1,1]}' https://cityiotest.mirage.city/api/table/dungeonmaster/
```
even if I put `{"grid":[0,1,1]}` in a file.

**Comment by yasushisakai** [comment]
53266a6 fixed it and confirmed the above curl was passed under the name `dungeonmaster-yasushi-testing` by increasing the payload limit to 4mb. For the record, this only applies to json payload.
