### ISSUE TITLE
Trailing slash inconsistency on cloned table

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_CityIO#126]
This might be a result of the cloning, but this works:
```
https://cityiotest.mirage.city/api/table/dungeonmaster/GEOGRIDDATA
```

This does not
```
https://cityiotest.mirage.city/api/table/dungeonmaster/GEOGRIDDATA/
```
I get a 405 error.

This table was created by cloning [dungeonmaster](https://cityio.media.mit.edu/api/table/dungeonmaster) (see #125)

In the original table (at cityio.media.mit.edu), both links work, with and without the trailing slash.

**Comment by yasushisakai** [comment]
7c4afd7 fixes this, the next server rollout will have this commit up and running.
