### ISSUE TITLE
Sever Is Down

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO#46]
```An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.

**Comment by yasushisakai** [comment]
something keeps killing the server

**Comment by RELNO** [comment]
@yasushisakai  since when? I've restarted it twice since an hour ago.

**Comment by yasushisakai** [comment]
should be back again, have made the json verification forgiving.

**Comment by RELNO** [comment]
Server is gone again, same error msg.
Please add restarting docs. for `BUS>1`

**Comment by yasushisakai** [comment]
https://github.com/CityScope/CS_CityIO_Backend/wiki/how-to-reboot-the-server

**Comment by popabczhang** [comment]
very useful, thanks

**Comment by agrignard** [comment]
Down again?

https://cityio.media.mit.edu/

**Comment by yasushisakai** [comment]
On again

**Comment by RELNO** [comment]
@yasushisakai FYI it's been forced restarted.

**Comment by yasushisakai** [comment]
What forced the restart?

**Comment by RELNO** [comment]
server was down,[so followed the holy wiki](https://github.com/CityScope/CS_CityIO_Backend/wiki/how-to-reboot-the-server).

**Comment by RELNO** [comment]
![image](https://user-images.githubusercontent.com/14296774/45265694-3588a900-b41d-11e8-90e2-765f23dca6b7.png)

**Comment by RELNO** [comment]
Back again, good reboot docs  🤛

**Comment by yasushisakai** [comment]
Thanks for covering @RELNO 

This time, I have some info that I can learn from.
This was different from what we were experiencing in the last two weeks.
Other processes (choice models, ((laundry scraper))) should be functioning fine.

It looks like by chance (and very small), CityMatrix and
CityMatrix_Volpe is writing in the same machine time,
hence overwhelmed. The library should take care of this, **but will take a look.**

**Comment by RELNO** [comment]
<img width="362" alt="screen shot 2018-09-22 at 22 11 09" src="https://user-images.githubusercontent.com/14296774/45923455-80da9700-beb4-11e8-8b25-4664ce78a804.png">

It was down again, this is the timestamp of restart for your logging/debugging

**Comment by RELNO** [comment]
Server is down. IMO this should be kept open until we're back to up time of ~a month ago.

**Comment by ChaoranChen** [comment]
502 bad gateway again.

**Comment by RELNO** [comment]
@yasushisakai @aberke fyi

**Comment by yasushisakai** [comment]
running

**Comment by RELNO** [comment]
@yasushisakai Mobility Choices is not restarting using `./boot.sh`, any idea?

**Comment by yasushisakai** [comment]
mocho should be running again

**Comment by agrignard** [comment]
@yasushisakai @RELNO should we close this issue, and write a more specific one related to the current issue?

**Comment by RELNO** [comment]
Server down

**Comment by RELNO** [comment]
down again

**Comment by yasushisakai** [comment]
💩

**Comment by RELNO** [comment]
http://cityio.media.mit.edu/ down again

**Comment by yasushisakai** [comment]
backon, running in debug mode.

**Comment by RELNO** [comment]
Server is down

**Comment by RELNO** [comment]
cityIO down

**Comment by RELNO** [comment]
back up

**Comment by RELNO** [comment]
Server is down
