### ISSUE TITLE
Legacy of a table

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO#49]
This page https://github.com/CityScope/CS_CityIO_Backend/wiki/Data-Mapping-of-Id-and-types is documenting a specific table (CityScope Volpe 1.0) in this wiki we explain what you can find in the 1.0 format.

On the 4th line of this page we put a link to the table which make sense. However with the current design of cityIo if the table is not strong enough to survive in the jungle and send some information every day it might be slowly dying and even eventually be remove from the list of active table (e.g if the server crashes). However it s important to have this link alive for documentation reason (e.g https://github.com/CityScope/CS_CityScopeJS_UI/issues/1)

So should we store (as an archive) some of the table. so that the link in this wiki for instance is always working?

**Comment by RELNO** [comment]
@agrignard one way - we can save a bunch of monolithic `JSON` examples for each API [1,2 etc] here under https://github.com/CityScope/CS_CityIO_Backend/tree/master/examples

**Comment by yasushisakai** [comment]
I do think the cityio server should act as a librarian; maintain table states and archival work.

which is tied to having a database (again) and caching etc. Assuming there will be iteration on this, it will take time so bare with me. 

In the mean time, I've added the citymatrix_volpe.json file as a dead sample. (c56649cda5683277b24fe3ec3ad5cba40419d40d)

**Comment by tuxun** [comment]
problem: for now everyone can erase a table from the mit server thinking he pushed it on the mit server instead of on his test server (I'm guilty, at least once). also testing client apps we got on the github erase mit server tables! (I started with the lego scanner, loaded the defaut 16x16.json in it)

**Comment by RELNO** [comment]
@tuxun what do you mean by test server? your local clone of cityIO server? If so, make sure you also fix GET/POST req. URLs in whatever tool you're trying to send to cityIO [CityScopeJS?]

As for 'deleting' a table -- as long as you perform POST requests you'll see your table alive. But yes -- if you stop sending and someone else use the same table name, it will be overwritten. To keep tables associated with users we need a log in/verification system, which, at this point is not implemented.

**Comment by tuxun** [comment]
(2weeks ago) i tried almost all client, and fixed urls where i saw them but sometimes i missed some of them (they are sometimes hard coded after a trap-ish definition). i cloned CityIO locally for avoid perturbation but earlier i was testing legotizer on your server, so i was erasing your tables (with your settings, so your name in it, clearly: good luck with that trying to debug your real table in real time.)  
I made short test and when i understood i was using the mit server and not my local cityio server i after that double checked hidden url :) 
For what i understood, lego real tables quickly erased my mistake, until someone else do it again (for exemple: grabbing json on github and putting them in the mit hosted legotizer.

**Comment by RELNO** [comment]
> so i was erasing your tables (with your settings, so your name in it, clearly: good luck with that trying to debug your real table in real time.)

You cannot 'erase' a table as it is only a temp json endpoint at this stage. At most you can overwrite it [e.g send your data over another table data] but it would be hard to understand why someone would do that, after all your local table will look like a mess... 

The bottom line is that -- at this point, when cityIO is still under development for the CityScope community -- setting up a table should not include a log in process. Yes, it's less secure, but no - debugging is as easy as looking at your table and seeing someone else's results on it. When we'll get to 50 new tables a day, we'll cross the bridge to auth  world..

**Comment by RELNO** [comment]
let me reittiere: EVERY time you post into cityIO, if your table name is not there, it will remake it.  So, let's say I deleted CityScope_tuxun_cooltable_1 using the cityIO front end -- still, if you keep on sending every second or so, the table will be there. Try it: remove https://cityio.media.mit.edu/api/table/citymatrix_volpe and see it back to life a click later.

**Comment by tuxun** [comment]
let me put it in other word: where is the virtual_table linked in https://github.com/CityScope/CS_CityIO_Backend ?

**Comment by RELNO** [comment]
>  where is the virtual_table linked in https://github.com/CityScope/CS_CityIO_Backend readme file?

I don't understand the question..which table? why readme?

**Comment by tuxun** [comment]
https://github.com/CityScope/CS_CityIO_Backend/blob/master/README.md 

> Data template link
You will find a sample table at examples/virtual_table.json folder.
direct link to virtual_table

**Comment by RELNO** [comment]
Got it -- virtual table is offline, thanks for flagging this. ref to https://github.com/CityScope/CS_CityIO_Backend/issues/45

**Comment by tuxun** [comment]
i just removed it cause you said "try"

**Comment by tuxun** [comment]
not everytable come back magically, that was the point, people running irl table have to know that night can break their unsaved table if they use the public server

**Comment by RELNO** [comment]
> not everytable come back magically, that was the point, people running irl table have to know that night can break their unsaved table if they use the public server

If you send (post) it's there, if not than it is not there. If you removed something and it is not back on, that is because THERE IS NO PHYSICAL TABLE. So thanks for cleaning up a non working table :)

**Comment by tuxun** [comment]
and it was not only a stale table, it was a documentation resource. if someone make a table for create a base on cityio server with legotizer (or for the sake of documentation) then dont update it anymore (not changing stuff on physical map), only working on view clients, any tester like me doing the mistake to test experiment as I did, can update their not owned table.
The first staled legotizer wont see the table change made by a second legotizer unless a change occurs on the first real table and it try to update the data, but meanwhile your view as changed.

Than mean if you dont move a lego on your real table, but someone else is using the same server virtual table than you, you can see visualization change apparently without reason, and start to try try to debug that.

I left school 15 year ago, giving me the impression I cant be the only fool having an interest in experimenting with your project, potentially introducing border effect if i start to run apps furbished on this github "as it". there is no "50 new tables a day" at the moment, but there will be a starting point where everyone will make the same mistake i made than update physical view without update physical change to real table, so we may have get 10 tables and 20 tester scratching their head: "why my table view is updated when when i dont move my physical table?" and i think its worst :D

**Comment by tuxun** [comment]
sorry that was a long point but:
- I felt guilty for had causing potential headaches, for me the legacy of table question implies
-  the version of api used (the documentation mention a virtualtable.json in v1 version, but they are filtered by the frontend, maybe rejected by the backend?)
-  the legacy of people updating it those solved, table on cityIO 
- the need to save special staled but still used version

**Comment by tuxun** [comment]
idea:
if (table.version==archivable)
{
save them somewhere unwritable for later
copy them with others
everyday restart restore all table normally, except for the archivable ones, which are restored from previous saved version
}

**Comment by RELNO** [comment]
archive [basically a database] is on our list of to do. For now, cityIO only works as an operator and has no real storage functionality.

**Comment by RELNO** [comment]
Storage/database is WIP, this conversion can continue as soon as it deployed. Closing.
