### ISSUE TITLE
Processing cityIO post 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO#61]
Issue #52 has been almost done.

What is missing now is how to pushing cityIO from a url.

I thought this could work (it works for a local file)

`````
saveJSONObject(mesh, "https://cityio.media.mit.edu/api/table/update/cityIO_Processing");
`````

but it's not what is the propoer way to post in processing?

**Comment by agrignard** [comment]
The last commit can push something but this is how it looks like

``````
{"meta":{"id":"28cbba0dbefa9dc81ea5c8027473bea378037f199c9281e5f349ce2a696225d8","timestamp":1552338764723,"apiv":"2.1.0"},"header":{"name":"","spatial":{"nrows":0,"ncols":0,"physical_longitude":0,"physical_latitude":0,"longitude":0,"latitude":0,"cellSize":0,"rotation":0},"owner":{"name":"","title":"","institute":""},"block":null,"mapping":null},"grid":null,"objects":null}
```````

looks like a default table, something is wrong in the string that i send 

``````
post.addData("https://cityio.media.mit.edu/api/table/update/cityIO_Processing", mesh.toString());
``````

where mesh is suppose to have the hole string

**Comment by yasushisakai** [comment]
stale issue, re-open if needed
