### ISSUE TITLE
New Virtual Table not compatible 2.1.0

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO#70]
https://cityio.media.mit.edu/api/table/virtual_table doesn't work anymore  with 2.1 

Current version 2.1 is https://github.com/CityScope/CS_CityIO_Backend/blob/master/examples/virtual_table.json

**Comment by agrignard** [comment]
In the current version 
we have ````"ncols":25,"nrows":25 ````however  grid is empty - >````"grid":[]````

**Comment by RELNO** [comment]
should be fine now https://cityio.media.mit.edu/api/table/virtual_table

**Comment by RELNO** [comment]
closing if there're no other issues

**Comment by agrignard** [comment]
There is still a problem in this file. The GAMA and Processing example doesn't work anymore with the specific file. Out of bounds in the grid, are you sure you have 500 value in the grid?

**Comment by agrignard** [comment]
last thing "apiv":"2.1" not  "apiv":"2.0" according to https://github.com/CityScope/CS_CityIO_Backend/wiki/cityIO-Data-Structure

**Comment by RELNO** [comment]
It's 2.1, so closing if no other issues
