### ISSUE TITLE
Cannot push to cityIO form GAMA

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO#74]
This model is supposed to provide a generic read/write to cityIO. It used to work the push doesn't work anymore

It is using this url, is it the right one?
`````
https://cityio.media.mit.edu/api/table/update/cityIO_Gama
`````
See https://github.com/CityScope/CS_CityIO_Backend/tree/master/examples/GAMA/cityIO_Gama/models

**Comment by yasushisakai** [comment]
let me look into it

**Comment by yasushisakai** [comment]
weird, I can see it posting in my local env... 

```java
	  	try{
	  	  //save(json_file("https://cityio.media.mit.edu/api/table/update/cityIO_Gama_Agent", outputMatrixData));
	  	  write(outputMatrixData);		
	  	  save(json_file("http://localhost:8080/api/table/update/test_gama", outputMatrixData));
```

this is what I did.  does the below config change anything?

![Capture](https://user-images.githubusercontent.com/1502180/56462454-593ba680-6391-11e9-843c-6160fbe7e05b.PNG)

**Comment by yasushisakai** [comment]
https://cityio.media.mit.edu/api/table/Gama_test_Agents
https://cityio.media.mit.edu/api/table/Gama_test_Grid

from:
https://github.com/CityScope/CS_CityIO_Backend/blob/gama_example_test/examples/GAMA/cityIO_Gama/models/cityIO.gaml

I see it running as expected??

**Comment by agrignard** [comment]
It is ok now. I don't what was not working on Friday. Thanks for having a look.

I am closing this issue
