### ISSUE TITLE
body size limit

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_CityIO#85]
turns out there is a [cap sending data](https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/) by nginx, I can let it eat more at once, what do you think?

**Comment by agrignard** [comment]
What is nginx? Are we using it? For now it seems that we are restricted to 2MB per push. That's maybe a good limit for now to restrict ourself to very light sending of data from application to application but I think that for a long term scalable solution we might want to have the possibility to upload the bigger file later (imagine a simulation that would return some sounds or energy consumption for 3D buildings it might be quickly much more bigger than 2MB).

**Comment by RELNO** [comment]
@yasushisakai seems [controlable](https://serverfault.com/questions/814767/413-request-entity-too-large-in-nginx-with-client-max-body-size-set)

**Comment by yasushisakai** [comment]
yeah, I've increased it to 4MB to re-post grasbrook manually.
The question might be (as pointed @agrignard) how do we think about it.


A distorted image of myself with 2000 x 2000 is under 50KB. just saying.
