### ISSUE TITLE
Virtual table missing

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO#86]
https://cityio.media.mit.edu/api/table/virtual_table

**Comment by RELNO** [comment]
thanks it should be back. @yasushisakai, here's the (unusual) error:

<img width="655" alt="Screen Shot 2019-07-29 at 13 53 05" src="https://user-images.githubusercontent.com/14296774/62070314-3a5a7500-b208-11e9-8b41-978700c8ef46.png">

**Comment by yasushisakai** [comment]
I see the virtual table, re-open if needed.
