### ISSUE TITLE
Table wrong name

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO#89]
There is some table that has a wrong name on the server
https://cityscope.media.mit.edu/CS_CityIO/

Like "Some(%22cityIO_Gama_Agent%22)" then the url appears like this Some("cityIO_Gama_Agent")

**Comment by RELNO** [comment]
error stems from here https://cityio.media.mit.edu/api/tables/list

**Comment by RELNO** [comment]
@agrignard do you maybe use "" in table name? see https://www.w3schools.com/tags/ref_urlencode.asp

**Comment by yasushisakai** [comment]
I've deleted the Some("table_name") entries, from the memory and the database, it shouldn't be there anymore unless you specifically send that string
