### ISSUE TITLE
cityIO 'choking' 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO#93]
<img width="936" alt="Screen Shot 2019-08-02 at 11 36 47" src="https://user-images.githubusercontent.com/14296774/62381606-de4e6400-b519-11e9-9e88-57cdd2b856b0.png">

Seen these errors in several `POST`ers

**Comment by yasushisakai** [comment]
Nginx or simple hardware cap of the cityio vm, or your vm/machine or a hiccup in Media lab network, regardless of the error, we saw that the cityio (process) kept running without an indication on my side. 

https://stackoverflow.com/questions/15820739/python-urlerror-urlopen-error-errno-10060

I recall  we did a try catch on this client, I would add some fallback error handling on top of it, or a logging system that we can investigate. (which quickly becomes an elaborated tool) but I think it is crucial for the sending side to be robust too. Cacheing un-sent table states is another path.
