### ISSUE TITLE
Implement clear functionality for fields 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO#95]
Now `https://cityio.media.mit.edu/api/table/clear/grasbrook/grid` won't work. Please allow to clear individual fields via post req

**Comment by RELNO** [comment]
@yasushisakai would be great to have this feature. At the time, looking to which filed are currently available for each table dictates frontend layer propagation. Therefore a remove function is important.

**Comment by yasushisakai** [comment]
#101 tackles to this issue

**Comment by RELNO** [comment]
> #101 tackles this issue

Great -- API is `clear_module`? 
If works I suggest you pull the PR, as you're the only one in the bus.

**Comment by RELNO** [comment]
What is the API for this?

**Comment by yasushisakai** [comment]
`https://cityio.media.mit.edu/api/table/clear/{tablename}/{modulename}`

thanks for the reminder, updated the wiki too.
