### ISSUE TITLE
cityio is down / 100% choked 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO#96]

**Comment by agrignard** [comment]
it's working for me

**Comment by agrignard** [comment]
working from Lyon

**Comment by RELNO** [comment]
Dead in Budapest ;)

**Comment by RELNO** [comment]
Update:
 Works on 3G connection. Ergo, this is due to some DDoS or firewall 'feature'.

**Comment by yasushisakai** [comment]
looks fine. Anything I should try?

**Comment by RELNO** [comment]
We managed to run it, but it was choking if more than one machine ran. It's not a cityio problem, but rather a ddos issue

**Comment by agrignard** [comment]
Not working from cell phone (3G or 4G) connection in France

**Comment by yasushisakai** [comment]
I can't see this by myself but we can try if services like https://1.1.1.1/ works?

**Comment by yasushisakai** [comment]
closing since not reproducible, may be TIMEOUT is less forgiving in 3G, LTE networks
