### ISSUE TITLE
Avoid cityIO hash breach via quantum supremacy  

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_CityIO#97]
Given recent publications concerning advancement in quantum supremacy [https://www.nature.com/articles/s41586-019-1666-5, https://www.nature.com/articles/d41586-019-03213-z] it is crucial to avoid hash breach via quantum processes. @yasushisakai can you take a look?

**Comment by yasushisakai** [comment]
will do.

Action Points:
change the hash function to something based on Lamport Signatures in combination with a Merkle tree.

**Comment by RELNO** [comment]
Couldn't find quantum computers on Amazon, closing for now.
