### ISSUE TITLE
Wiki structure

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO#99]
@yasushisakai what about creating a dedicated page with proposal

I am just thinking if this is still relevant
https://github.com/CityScope/CS_CityIO/wiki/v0.3.0-proposal
https://github.com/CityScope/CS_CityIO/wiki/v0.4.0-Proposal

**Comment by yasushisakai** [comment]
consolidated a place for Proposals, Milestones, and Changelogs
https://github.com/CityScope/CS_CityIO/wiki/Proposals,-Milestones,-and-Changelogs

Currently, I'm the only one developing so I thought it's ok to have these three in the same place.

**Comment by agrignard** [comment]
Thnaks, it's usefull for this issue https://github.com/CityScope/cityscope.github.io/issues

**Comment by yasushisakai** [comment]
a bit lost here, do we have anything we should do for this repo's wiki??

**Comment by yasushisakai** [comment]
closing from no response, re-open if needed
